export const dumyInitialValues = {
  student_school: "Greenwood High School",
  student_programs: "Computer Science",
  student_degree: "Bachelor of Science (B.Sc.)",
  student_specialisation: "Design Management",
  student_how_did_you_hear_about_us: "Word of Mouth",
  student_profile_image: null, // or use "" if you prefer
  student_first_name: "Faizan",
  student_middle_name: "Sabir",
  student_last_name: "Shaikh",
  student_nationality: "Indian",
  student_address: "Byculla",
  student_apartment: "Tehseen Tower",
  student_country: "India",
  student_state: "Maharashtra",
  student_city: "Mumbai",
  student_postal_code: "40008",
  student_phone_number: "7666129168",
  student_email: "sf48116@gmail.com",
  DD: "30",
  MM: "11",
  YYYY: "1999",
  student_gender: "Male",
  student_blood_group: "A+",
  student_caste_category: "General",
  student_instagram_url: "https://www.instagram.com/izancode/",
  student_linkedin_url: "https://www.linkedin.com/in/izancode/",
  previous_college_grade_10_details: "B",
  previous_college_percentage_grade_secured: "60",
  previous_college_marks_secured: "319",
  previous_college_marks_out_of: "400",
  previous_college_academic_year: "2020-2021",
  previous_college_examination_board: "State Board of Maharashtra",
  previous_college_state: "Maharashtra",
  previous_college_city: "Mumbai",
  previous_college_grade_12th_school_details: "58",
  previous_college_name: "Maharashtra College",
  student_father_name: "Sabir Shaikh",
  student_father_occupation: "Business",
  student_father_number: "9892306284",
  student_father_email: "father@gmail.com",
  student_mother_name: "Ruqaiyya",
  student_mother_occupation: "Housewife",
  student_mother_number: "9987394168",
  student_mother_email: "mother@gmail.com",
  in_case_of_guardian_please_specify_the_relationship: "No",
  statement_of_purpose: "Just for testing",
};
