export const initialValues = {
  student_school: "ATLAS School of Management",
  student_programs: "Post Graduate Degree",
  student_degree: "M.Des",
  student_specialisation: "Design Management",
  student_how_did_you_hear_about_us: "Online Advertisement",
  student_profile_image: null,
  student_first_name: "John",
  student_middle_name: "A.",
  student_last_name: "Doe",
  student_nationality: "American",
  student_address: "123 Main Street",
  student_apartment: "Apt 4B",
  student_country: "USA",
  student_state: "California",
  student_city: "Los Angeles",
  student_postal_code: "90001",
  student_phone_number: "7666129168",
  student_email: "john.doe@example.com",
  DD: "15",
  MM: "08",
  YYYY: "1990",
  student_gender: "Male",
  student_blood_group: "O+",
  student_caste_category: "General",
  student_instagram_url: "https://www.instagram.com/johndoe/",
  student_linkedin_url: "https://www.linkedin.com/in/johndoe/",
  previous_college_grade_10_details: "ABC High School",
  previous_college_percentage_grade_secured: "85%",
  previous_college_marks_secured: "425",
  previous_college_marks_out_of: "500",
  previous_college_academic_year: "2006-2007",
  previous_college_examination_board: "State Board",
  previous_college_state: "California",
  previous_college_city: "Los Angeles",
  previous_college_grade_12th_school_details:
    "Vifvvfvvekananda Kendra Vidyalaya",
  previous_college_name: "University of California",
  student_father_name: "Richard Doe",
  student_father_occupation: "Engineer",
  student_father_number: "7666129168",
  student_father_email: "richard.doe@example.com",
  student_mother_name: "Jane Doe",
  student_mother_occupation: "Teacher",
  student_mother_number: "7666129168",
  student_mother_email: "jane.doe@example.com",
  in_case_of_guardian_please_specify_the_relationship: "N/A",
  statement_of_purpose:
    "I am applying to further my education and career in design management. My goal is to acquire advanced knowledge and skills to contribute to innovative projects in the industry.",
};
