export const dumyInitialValues = {
  faculty_id: 55555, // Or you can use `undefined` if you prefer
  department: "Computer Science",
  designation_position: "Assistant Professor",
  qualification: "Ph.D. in Computer Science",
  experience_in_year: "5 years",
  courses_subjects_taught: "Introduction to Programming",
  faculty_profile_image: null, // Or you can use `null` if no image
  faculty_first_name: "Faizan",
  faculty_middle_name: "Sabir",
  faculty_last_name: "Shaikh",
  faculty_nationality: "Indian",
  faculty_address: "Byculla",
  faculty_apartment: "Tehseen Tower",
  faculty_country: "India",
  faculty_state: "Maharashtra",
  faculty_city: "Mumbai",
  faculty_postal_code: "40008",
  faculty_phone_number: "7666129168",
  faculty_email: "sf48116@gmail.com",
  DD: "30",
  MM: "11",
  YYYY: "1999",
  faculty_gender: "Male",
  faculty_instagram_url: "https://www.instagram.com/izancode/",
  faculty_linkedin_url: "https://www.linkedin.com/in/izancode/",
  research_interests_if_applicable: "just for testing",
  publications_if_applicable: "just for testing",
};
