export const initialValues = {
  faculty_id: null, // Or you can use `undefined` if you prefer
  department: "",
  designation_position: "",
  qualification: "",
  experience_in_year: "",
  courses_subjects_taught: "",
  faculty_profile_image: "", // Or you can use `null` if no image
  faculty_first_name: "",
  faculty_middle_name: "",
  faculty_last_name: "",
  faculty_nationality: "",
  faculty_address: "",
  faculty_apartment: "",
  faculty_country: "",
  faculty_state: "",
  faculty_city: "",
  faculty_postal_code: "",
  faculty_phone_number: "",
  faculty_email: "",
  DD: "",
  MM: "",
  YYYY: "",
  faculty_gender: "",
  faculty_instagram_url: "",
  faculty_linkedin_url: "",
  research_interests_if_applicable: "",
  publications_if_applicable: "",
};
