export const initialValues = {
  faculty_id: 2345432,
  department: "Post Graduate Degree",
  designation_position: "M.Des",
  qualification: "Design Management",
  experience_in_year: "Online Advertisement",
  courses_subjects_taught: "Online Advertisement",
  faculty_profile_image: null,
  faculty_first_name: "John",
  faculty_middle_name: "A.",
  faculty_last_name: "Doe",
  faculty_nationality: "American",
  faculty_address: "123 Main Street",
  faculty_apartment: "Apt 4B",
  faculty_country: "USA",
  faculty_state: "California",
  faculty_city: "Los Angeles",
  faculty_postal_code: "90001",
  faculty_phone_number: "7666129168",
  faculty_email: "john.doe@example.com",
  DD: "15",
  MM: "08",
  YYYY: "1990",
  faculty_gender: "Male",
  faculty_instagram_url: "https://www.instagram.com/izancode/",
  faculty_linkedin_url: "https://www.linkedin.com/in/johndoe/",
  research_interests_if_applicable: "N/A",
  publications_if_applicable:
    "I am applying to further my education and career in design management. My goal is to acquire advanced knowledge and skills to contribute to innovative projects in the industry.",
};
